### ISSUE TITLE
Swagger2Controller.getDocumentation get IndexOutOfBoundsException for version of 2.4.0

### ISSUE THREAD

**Issue by aqlu** [springfox/springfox#1306]
When upgrade to 2.4.0 and  request parameter is "java.util.Map", IndexOutOfBoundsException will be happend, and I used 2.2.2 its ok!   This issue it like's #1129 , looks not completely repair :)

spring RestController API: 
```
@RequestMapping(method = RequestMethod.GET)
public BaseQueryResponse<MobCate> getMobCates(@RequestParam Map<String, String> paramMap) {
 ...
}
```

stack trace:
```

java.lang.IndexOutOfBoundsException: Index: 1
	at java.util.Collections$EmptyList.get(Collections.java:4454) ~[na:1.8.0_45]
	at springfox.documentation.swagger2.mappers.ModelMapper.typeOfValue(ModelMapper.java:129) ~[springfox-swagger2-2.4.0.jar:2.4.0]
	at springfox.documentation.swagger2.mappers.ModelMapper.mapProperties(ModelMapper.java:92) ~[springfox-swagger2-2.4.0.jar:2.4.0]
	at springfox.documentation.swagger2.mappers.ModelMapper.mapModels(ModelMapper.java:67) ~[springfox-swagger2-2.4.0.jar:2.4.0]
	at springfox.documentation.swagger2.mappers.ModelMapper.modelsFromApiListings(ModelMapper.java:202) ~[springfox-swagger2-2.4.0.jar:2.4.0]
	at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl.mapDocumentation(ServiceModelToSwagger2MapperImpl.java:50) ~[springfox-swagger2-2.4.0.jar:2.4.0]
	at springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(Swagger2Controller.java:81) ~[springfox-swagger2-2.4.0.jar:2.4.0]
```

**Comment by dilipkrish** [comment]
Thanks for reporting. Will take a look

**Comment by dilipkrish** [comment]
While the reported problem is fixed, this doesn't handle the map types correctly. Fix needs to handle map types [here](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/SerializableParameterFactories.java#L79-L83)

**Comment by srinikandula** [comment]
I think I still see the problem in 2.5.0. Any help that you can offer?

> at java.util.Collections$EmptyList.get(Collections.java:4454)
>         at springfox.documentation.swagger2.mappers.ModelMapper.typeOfValue(ModelMapper.java:129)
>         at springfox.documentation.swagger2.mappers.ModelMapper.mapProperties(ModelMapper.java:92)
>         at springfox.documentation.swagger2.mappers.ModelMapper.mapModels(ModelMapper.java:67)
>         at springfox.documentation.swagger2.mappers.ModelMapper.modelsFromApiListings(ModelMapper.java:205)
>         at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl.mapDocumentation(ServiceModelToSwagger2MapperImpl.java:50)
>         at springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(Swagger2Controller.java:82)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by dilipkrish** [comment]
@srinikandula Not without more details.. 

Also this is a very old issue, please open a new issue if you feel its a new issue, it will help us prioritize it better.
