### ISSUE TITLE
request to support nested generic of map

### ISSUE THREAD

**Issue by namkee** [springfox/springfox#1312]
hi. 
i use latest version of springfox (2.4.0).

I want to generate swagger documentation of all of our company services API. I've faced several problems while generating swagger document from RESTful API source code(spring MVC ) through  springfox. most difficult problem is to generate swagger model of generic model value of map. like this..

    @RequestMapping(value = "/world/map-test", method = RequestMethod.GET)
    @ResponseBody
    public Map<String, List<Long>> test1() {
        //.. ignore ..
        return null;
    }

in the above case springfox was wrong generate swagger document. there is not 'List' model in definitions entity.

    /api/world/map-test: {
        get: {
            responses: {
                200: {
                    description: "OK",
                    schema: {
                        type: "object",
                        additionalProperties: {
                            $ref: "#/definitions/List"
                        }
                    }
                }
            },

In the code of ModelMapper.java (method modelRefToProperty) response property generation is restricted only first generic class.
for support nested generic response, change modelRefToProperty code to recursive method.
https://github.com/namkee/springfox/commit/3215f25f1e303fa2c23d8ff49daacaedd5364390

is there reason for restrict support multi-level generic model? and this problem is known issue?
do you have a plan to support multi-level generic model?
I hope to springfox support this as soon as possible. is there anything i can do for this?

thanks.

**Comment by dilipkrish** [comment]
@namkee could you try with 2.4.1-SNAPSHOT? I think this has been fixed

**Comment by namkee** [comment]
i was tried with 2.4.1-SNAPSHOT... but not fixed.
checked inside of Swagger2Controller. DocumentCache got correct response data. but after result of 'mapper.mapDocumentation(documentation)`. Swagger object got wrong response data.

#debug window of Documentation Object.
![2016-05-17 10 33 14](https://cloud.githubusercontent.com/assets/8230920/15308787/cbf3f918-1c1b-11e6-9862-22b20f0c6c44.png)

#debug window of after mapper generate Swagger Object
![2016-05-17 10 34 19](https://cloud.githubusercontent.com/assets/8230920/15308792/dcefc68e-1c1b-11e6-969b-4438e01a92e9.png)

do you have any idea about this?
