### ISSUE TITLE
Springfox overwrites swagger path entries with the same base path but with different content types

### ISSUE THREAD

**Issue by codecounselor** [springfox/springfox#1367]
The mapping code in scope for this request is the same as in issue #1053. 

Content Negotiation is a widely adopted solution for returning various representations of the same API resource by way of setting the HTTP Allow Header.

There is an open feature request for the swagger spec to support multiple response schemas per path: OAI/OpenAPI-Specification#146
Until this is implemented the usefulness of what I'm about to propose will be admittedly limited, but still useful.

Here is an example of the controller implementation:

``` java
  @RequestMapping(value = "/{itemId}", method = RequestMethod.GET, produces = "application/vnd.com.flex.inventory-summary+json")
  public ResponseEntity<InventoryItemSummary> findIdentityById(@PathVariable String itemId) {
    return new ResponseEntity<InventoryItemSummary>(summary, HttpStatus.OK);
  }

  @RequestMapping(value = "/{itemId}", method = RequestMethod.GET, produces = "application/vnd.com.flex.inventory-basic+json")
  public ResponseEntity<InventoryItemBasic> findById(@PathVariable String itemId) {
    return new ResponseEntity<InventoryItemBasic>(item, HttpStatus.OK);
  }
```

The resulting swagger output looks like:

```
"/inventory/{itemId}": {
      "get": {
        "tags": [
          "inventory-item-controller"
        ],
        "summary": "findById",
        "operationId": "findByIdUsingGET",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/vnd.com.flex.inventory-basic+json"
        ],
```

where the desired output would include both entries in the produces field, like this:

```
"produces": [
          "application/vnd.com.flex.inventory-basic+json",
          "application/vnd.com.flex.inventory-summary+json"
        ],
```

Right now this serves as a form of documentation in SwaggerUI, eventually it will aid in client SDK generation.  Based on the limitation imposed by Swagger, my current thought is to somehow denote one of the methods as "primary" so that anyone wishing to generate a client SDK will get the correct schema.  

It seems that the path which springfox maps is consistent, but I haven't look closely enough at the code to validate if or why that is the case.

If there is agreement this would be a nice feature to add, we can discuss implementation options.  I'll happily submit a PR.

**Comment by dilipkrish** [comment]
@codecounselor let me think it over and get back. Gut feel looking at your suggestion is this what I'd initially intended it to work.

**Comment by ssevertson** [comment]
Is this a regression of #711 that was marked as fixed/released back in 2.1.0/2015-07?

**Comment by dilipkrish** [comment]
@ssevertson No this is a new feature request. This for when you have different responses based on accept header

**Comment by ssevertson** [comment]
@dilipkrish OK, it's just confusing because #711 has comments/examples related to differing accept headers (aka @RequestMapping on methods with the same path, but different produces = {} statements).

**Comment by codecounselor** [comment]
Sorry I am only responding now.  To me, it looks to be the same issue.  I thought I did a pretty exhaustive search before logging this one, I must have missed it.  Was that actually fixed? I did a quick scan of the merge commit and didn't see any changes in `ServiceModelToSwagger2Mapper`.  But I know little about the codebase so that may not have any actual bearing on the matter.

**Comment by rainoko** [comment]
Is this really fixed. I have issue with springfox data rest.
Spring data rest with hateoas creates two methods for GET one for compact collection and one for normal collection

I see both in Documentation cache
But ServiceModelToSwagger2Mapper overwrites one with another

```
private Path mapOperations(ApiDescription api, Optional<Path> existingPath) {
    Path path = existingPath.or(new Path());
    for (springfox.documentation.service.Operation each : nullToEmptyList(api.getOperations())) {
      Operation operation = mapOperation(each);
      path.set(each.getMethod().toString().toLowerCase(), operation);
    }
    return path;
  }
```
path.set(each.getMethod().toString().toLowerCase(), operation)
if i have multiple operators for same api it preserves only last.

**Comment by dilipkrish** [comment]
Are you saying that the new combined operation does not have _one_ operation with _both_ media types?

**Comment by rainoko** [comment]
No I have separate operations
![capture2](https://cloud.githubusercontent.com/assets/7591356/25533614/e20a476e-2c39-11e7-90ce-d564e0bf486e.PNG)
![capture1](https://cloud.githubusercontent.com/assets/7591356/25533615/e20bb69e-2c39-11e7-9f5e-4730352ec3ea.PNG)

**Comment by dilipkrish** [comment]
This has been re-written in #1623. Would be great to get some feedback on the changes. I suspect this bug will have been fixed.

**Comment by dilipkrish** [comment]
Yes I believe its a bug that has been addressed since (3.0.0)

**Comment by rainoko** [comment]
We made workaround as following. We consolidated all same path and different content type header request-handlers into same method and with if or switch statements we choose actual implementation. This works good enough. Swagger shows dropdown list for content type and accept headers. Only problem is that different content type means different models (we use headers for versioning) and swagger won't show model descriptions for eachof them. This is addressed in openapi spec v3.0 but right now we just have to accept this.

**Comment by dakagui** [comment]
Unfortunately still reproducing this issue exactly as above in version 3.0.0-SNAPSHOT.

**Comment by ShuWang00** [comment]
> We made workaround as following. We consolidated all same path and different content type header request-handlers into same method and with if or switch statements we choose actual implementation. This works good enough. Swagger shows dropdown list for content type and accept headers. Only problem is that different content type means different models (we use headers for versioning) and swagger won't show model descriptions for eachof them. This is addressed in openapi spec v3.0 but right now we just have to accept this.

What do you mean by consolidate? Could you give a specific example?
