### ISSUE TITLE
ApiImplicitParams documentation lacks Model and Model Schema for user-defined types

### ISSUE THREAD

**Issue by richmeyer7** [springfox/springfox#1540]
The Swagger 2.6.0 generated documentation for an ApiOperation with ApiImplicitParams that specifies dataType as a user-defined type lacks the Model and Model Schema for the user-defined type. Instead, it shows the Data Type as "string":

![image](https://cloud.githubusercontent.com/assets/11902511/19614493/9be26cea-97aa-11e6-911a-a56d6e5b4b97.png)

![image](https://cloud.githubusercontent.com/assets/11902511/19614438/180010d0-97aa-11e6-82a2-0d8893ca4e57.png)

Investigating in the debugger, I found that method springfox.documentation.swagger.readers.operation.maybeGetModelRef(ApiImplicitParam) rejects the user-defined type (for example dataType = "LinkCreateBean") because it is not contained in the predefined types in springfox.documentation.schema.Types.baseTypes. The following code is where the method changes the type to "string":

    if (!isBaseType(param.dataType())) {
      LOGGER.warn("Coercing to be of type string. This may not even be a scalar type in actuality");
      baseType = "string";
    }

When, in the debugger after that block executes, I change the "baseType" variable back to "LinkCreateBean" (which is one of our user-defined types created via annotation @ApiModel), the Swagger UI shows the Data Type as LinkCreateBean, and shows the Model and Model Schema exactly as we specified:

![image](https://cloud.githubusercontent.com/assets/11902511/19614531/fdbb9414-97aa-11e6-9c72-aaa7ad87b581.png)

![image](https://cloud.githubusercontent.com/assets/11902511/19614463/46a1a89a-97aa-11e6-90fb-e61c2a592a0f.png)

![image](https://cloud.githubusercontent.com/assets/11902511/19614469/5744a8e6-97aa-11e6-8fba-b2d80b52fbc2.png)

It seems that method springfox.documentation.swagger.readers.operation.maybeGetModelRef(ApiImplicitParam) needs to be fixed to match param.dataType() against all user-defined (@ApiModel) types, not just check isBaseType().

Also, I recommend renaming variable "baseType" to "dataType".

**Comment by dilipkrish** [comment]
Fixed via #1529

**Comment by dilipkrish** [comment]
This is a duplicate of #1545

**Comment by filip-majernik** [comment]
In which version has this been fixed? I am using the 2.7.0 and the problem is still there. Any class defined as a dataType or dataTypeClass is ignored.

**Comment by dilipkrish** [comment]
The `dataType` needs to be a fully qualified class @filip-majernik

**Comment by rohitiyengar** [comment]
@dilipkrish I am referencing a model with a fully qualified class name. It still doesn't work for me. I am using 2.6.1.

```
@ApiImplicitParams(@ApiImplicitParam(name = "requestBody", paramType = "body", required = true, value = "desc", dataType = "com.example.ClassName"))
```

The datatype on the Swagger UI shows up as "com.example.ClassName". Am I missing something?

**Comment by dilipkrish** [comment]
@rohitiyengar yes you are not using 2.7.0.

**Comment by rohitiyengar** [comment]
@dilipkrish Tried that, still doesn't work.
