### ISSUE TITLE
[Bug? - 2.6.1] JAXB annotations are ignored when generating model

### ISSUE THREAD

**Issue by ghilainm** [springfox/springfox#1583]
JAXB annotations are ignored when generating the model and I have no way (I know) to customize the model generated. Therefore the swagger.json is completely wrong.

```
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Class used to answer to requests when there is an error (for example no ccn session id or invalid session id)
 */
@XmlRootElement(name = "TICKET_RESPONSE")
public class TicketResponse {

    private Error error;

    @XmlElement(name = "ERROR")
    public Error getError() {
        return error;
    }

    public void setError(Error error) {
        this.error = error;
    }
}
```

Here is the model generated:

```
TicketResponse {
error (Error, optional)
}Error {
description (string, optional)
}
```

I was expecting this:

```
TICKET_RESPONSE {
ERROR (Error, optional)
}Error {
description (string, optional)
}
```

Did I miss something :)?

**Comment by ghilainm** [comment]
If I could override using ApiModelProperty(name="some custome name") it would be fine but it seems it doesn't work.

**Comment by dilipkrish** [comment]
@ghilainm JAXB annotations _will be_ ignored unless you have a dependency on 

```xml
<dependency>
  <groupId>com.fasterxml.jackson.module</groupId>
  <artifactId>jackson-module-jaxb-annotations</artifactId>
  <version>LATEST</version>
</dependency>
```

**Comment by ghilainm** [comment]
@dilipkrish Why is it necessary as JAXB annotations are part of the standard JRE?

**Comment by dilipkrish** [comment]
@ghilainm it is necessary for the jakson serializer to adapt models annotated with jaxb annotations to json.

**Comment by ghilainm** [comment]
I implemented it partially using the plug in mechanism and without any Jackson library therefore I think you could easily relax your constraint to support them without additional libraries!

**Comment by dilipkrish** [comment]
Its not springfox that is placing this constraint. It is jackson. There are issues to support other serialization libraries, but for now jackson is the only library supported

**Comment by derick1156** [comment]
I added the dependency mentioned above to my pom file and am still seeing my jaxb annotations ignored. Not sure what I could be doing wrong here. Any other suggestions?

**Comment by dilipkrish** [comment]
Looks like you're not using a boot application. You'll need to register the jackson module as [described here](https://github.com/FasterXML/jackson-module-jaxb-annotations)

**Comment by derick1156** [comment]
Thank you. So I registered the module on my HttpMessageConverter following the documentation you referenced and springfox is recognizing my @XmlElement Jaxb annotation now, but not my @XmlElementWrapper or @XmlRootElement annotations, any ideas why that may be? Here is an example of my Class:

@XmlRootElement(name= "restResponse" )
@XmlType(propOrder = {"status", "request", "employees"})
@JsonPropertyOrder({"status", "request", "employees"})
@JsonInclude(JsonInclude.Include.NON_NULL)
public class GetEmployeesRestResponse {
    @ApiModelProperty(position=0)
    private PagingStatus status;

    @ApiModelProperty(position=1)
    private EmployeeRequest request;

    @ApiModelProperty(position=2)
    private List<Employee> employees;

    public PagingStatus getStatus() {
        return status;
    }

    public void setStatus(PagingStatus status) {
        this.status = status;
    }

    public EmployeeRequest getRequest() {
        return request;
    }

    public void setRequest(EmployeeRequest request) {
        this.request = request;
    }

    @JsonProperty(value = "employees")
    @XmlElementWrapper(name = "employees", required = false, nillable = false)
    @XmlElement(name = "employee", required = false, nillable = false)
    public List<Employee> getEmployees() {
        if (null != employees) {
            return (employees.size() > 0 ? employees : null);
        } else {
            return null;
        }
    }

    public void setEmployees(List<Employee> employees) {
        this.employees = employees;
    }

**Comment by ghilainm** [comment]
@dilipkrish I believe you are wrong. I have added no dependencies manually and still the json conversion is working on my side. Therefore I guess that the dependency is simply pulled by spring-boot, therefore it should work out of the box with spring-boot standard dependencies on the classpath.

**Comment by dilipkrish** [comment]
For spring boot yes... for regular spring mvc NOT. Thats what I thought [I said](https://github.com/springfox/springfox/issues/1583#issuecomment-269568801).

**Comment by ghilainm** [comment]
@dilipkrish I didn't mention I was using spring boot but I am and this is not working, so I guess there is a bug.

**Comment by dilipkrish** [comment]
@ghilainm I suspect you have multiple ObjectMappers in play and the object mapper used to infer the schema isn't the same one the jaxb module has been applied to. Hard to tell without seeing your app and how its configured.

**Comment by davidporter65** [comment]
I'm having the same problem with a Spring boot application. Is there a demo of this working anywhere?

**Comment by dilipkrish** [comment]
@davidporter65 thats not how the `ObjectMapperConfigured` is intended to be used. You need to either
1. create an event handler for that event listener (implement `ApplicationListener<ObjectMapperConfigured>` and configure the object mapper that is passed in with the `JaxbAnnotationModule`.
2. Create/register an `ObjectMapper` bean.

**Comment by elonderin** [comment]
i (still) can get the @XmlRootElement(name = "my-custom-name") working with Spring Boot 2.0.0 and springfox 2.9.2

i just tried to reproduce this with the sample spring app (https://github.com/swagger-api/swagger-samples/ ) but 
a) this aint work for me -- eg. i get a 404 with http://localhost:8080/pets/1, /swagger-resources, ... despite the log claiming that these URLs are bound
b) this is using an older spring boot version, so might not be applicable anyhow

so, until i have proof otherwise,  could u plz just confirm that this to ur knowledge fixed?

if i have time i will try to setup an own sample project for this issue
