### ISSUE TITLE
Bug: UUID parameters don't have format "uuid"

### ISSUE THREAD

**Issue by dominik-jastrzebski** [springfox/springfox#2314]
I'm using springfox 2.8.0.

The following piece of code:

```
@RestController
public class NotificationApi {
@ApiOperation(nickname = "markNotificationDelivered", value = "Mark a notification as delivered.")
    @RequestMapping(path = "notifications/{id}/delivered", method = RequestMethod.POST)
    void markNotificationDelivered(@PathVariable("id") UUID id) {

    }
}
```

is converted to:

```
"/notifications/{id}/delivered" : {
      "post" : {
        "tags" : [ "notification-api" ],
        "summary" : "Mark a notification as delivered.",
        "operationId" : "markNotificationDelivered",
        "schemes" : [ ],
        "consumes" : [ "application/json" ],
        "produces" : [ "*/*" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "examples" : { },
            "headers" : { }
          }
        },
        "security" : [ ]
      }
    }
```

The problem is that parameter `id` doesn't have `"format": "uuid"` set. When I annotate the parameter with `@ApiParam(format = "uuid") @PathVariable("id")`, there is still no `format` in the Swaggerfile.

**Comment by dilipkrish** [comment]
Thanks for reporting

**Comment by dominik-jastrzebski** [comment]
@dilipkrish Any ideas for a workaround to make UUID parameters serialize with "format": "uuid" in the Swaggerfile?

**Comment by dilipkrish** [comment]
It needs to be fixed. Currently it is treated as a [primitive string](https://github.com/springfox/springfox/blob/cd58acaff89e8eb6d38d3eb247e3d99564446d36/springfox-schema/src/main/java/springfox/documentation/schema/Types.java#L80)

**Comment by dominik-jastrzebski** [comment]
I managed to hotfix this with plugins:

```
@Component
public class ApiModelPropertyBuilderExtensions implements ModelBuilderPlugin {

    @Override
    public void apply(ModelContext context) {
        Map<String, ModelProperty> updatedProperties =
                modelPropertiesWithUpdatedResolvedTypes(context.getBuilder().build().getProperties());
        context.getBuilder().properties(updatedProperties);
    }

    private Map<String, ModelProperty> modelPropertiesWithUpdatedResolvedTypes(
            Map<String, ModelProperty> originalModelProperties) {
        return originalModelProperties.entrySet().stream().map(entry -> {
            ModelProperty modelProperty = entry.getValue();
            modelProperty.updateModelRef(resolvedType -> {
                if (resolvedType != null && resolvedType.isInstanceOf(UUID.class)) {
                    return new ModelRef("uuid");
                } else {
                    return modelProperty.getModelRef();
                }
            });
            return new AbstractMap.SimpleEntry<>(entry.getKey(), modelProperty);
        }).collect(Collectors.toMap(AbstractMap.SimpleEntry::getKey, AbstractMap.SimpleEntry::getValue));
    }

    @Override
    public boolean supports(DocumentationType delimiter) {
        return true;
    }
}
```

```
@Component
public class ApiParametersBuilderExtensions implements ParameterBuilderPlugin {

    @Override
    public void apply(ParameterContext parameterContext) {
        ParameterBuilder parameterBuilder = parameterContext.parameterBuilder();
        ResolvedMethodParameter methodParameter = parameterContext.resolvedMethodParameter();
        ResolvedType parameterType = methodParameter.getParameterType();

        if (parameterType.isInstanceOf(UUID.class)) {
            parameterBuilder.modelRef(new ModelRef("uuid"));
        }
    }

    @Override
    public boolean supports(DocumentationType delimiter) {
        return true;
    }
}
```

**Comment by dilipkrish** [comment]
@dominik-jastrzebski thanks for sharing your solution! FYI a fix will land for this bug as well.

**Comment by ASaunin** [comment]
I have updated my dependencies up to 2.9.2 release, but this issue is still present

**Comment by dilipkrish** [comment]
> issue is still present
What issue are you facing? Is the json not right or does it now show in swagger-ui?

**Comment by ASaunin** [comment]
UUID field is still defined as String in JSON
Controller source code:
```
@PutMapping("/{id}")
public ResponseEntity<TenantInfo> update(@PathVariable("id") UUID id, @Valid @RequestBody UpdateTenant request) {
   ...
}```
JSON fragment (`.../api-docs`):
```

**Comment by dilipkrish** [comment]
Not sure. Seems like it was working in the [commit](https://github.com/springfox/springfox/commit/121db6c7064e15988ae22b22a57dc0014e384b62) above 👆

**Comment by ASaunin** [comment]
I've checked the details...
The main issue is fixed in fact. But the model is still displaying `UUID` as `String`.
Here is the JSON fragment:
![image](https://user-images.githubusercontent.com/19559375/41875804-ae58b066-78d4-11e8-8b6f-639d241ffeff.png)
Here is swagger-ui view:
![image](https://user-images.githubusercontent.com/19559375/41875949-0da85a8a-78d5-11e8-816e-678bfdfc8195.png)

**Comment by dilipkrish** [comment]
That would be an issue for [Swagger-ui](https://github.com/swagger-api/swagger-ui)

**Comment by dJani97** [comment]
As of now, this is still an issue on swagger-ui. Code examples are useless this way. Did somebody report this as a bug? Do they work on it?
