### ISSUE TITLE
latest springfox-swagger2 + springfox-swagger-ui throws class not found exception

### ISSUE THREAD

**Issue by zappee** [springfox/springfox#2364]
- [ ] What version of the library are you using? Is it the latest version?
```
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger2</artifactId>
    <version>2.8.0</version>
</dependency>
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger-ui</artifactId>
    <version>2.8.0</version>
</dependency>
```

What kind of issue is this? **Bug report**

I use _Spring Boot 2.0.1.RELEASE_ + _Jersey_ (spring-boot-starter-jersey).
The application works fine but after I add _@EnableSwagger2_ annotation to _Application.java_ I get a `java.lang.ClassNotFoundException: org.springframework.web.servlet.HandlerMapping` exception.

Demo project to demonstrate the issue: [https://github.com/zappee/swagger-bug](https://github.com/zappee/swagger-bug)

**Comment by dilipkrish** [comment]
Spring boot 2.x isnt officially supported yet. But thanks for reporting this issue.

**Comment by benjaminkomen** [comment]
I have the same issue. with springfox 2.9.2

**Comment by walec51** [comment]
I' getting various ClassNotFound exceptions or FileNotFound on classpath resources if I add the springfox-bean-validators library to my classpath

PS. using 2.9.2

**Comment by dilipkrish** [comment]
This should be fixed as part of the spring 5.0, spring boot 2.0 support via #1773  in 3.0.0 of the library.

**Comment by Bryksin** [comment]
Still the same problem:
Swagger: 2.9.2, Spring Boot 2.2.0.M6 - Hoxton.M2

**Comment by klsnreddy** [comment]
I am also facing the same issue with Spring boot 2.1.0 and Springfox 2.9.2.
Any resolution to this?

**Comment by RamP156** [comment]
I am having this issue as well. Is there any update?

**Comment by erycoking** [comment]
I am also facing this issue. anyone found a solution?? 
kindly share

**Comment by dilipkrish** [comment]
It’s been fixed and will be released shortly

**Comment by xsank** [comment]
still with the problem.
springboot 2.1.1.RELEASE, swagger 2.9.2

**Comment by xsank** [comment]
> 

now i use springboot 2.3.1.RELEASE, swagger 3.0.0

**Comment by tuoqiao** [comment]
still with the problem.
springboot 2.6.13, swagger 2.10.5
