### ISSUE TITLE
Jackson + Swagger + jackson2HttpMessageConverter causes invalid json ouput of api-doc when setting WRAP_ROOT_VALUE to true

### ISSUE THREAD

**Issue by t0tec** [springfox/springfox#597]
When setting Jackson serialization feature `WRAP_ROOT_VALUE` to `true` it spits out incorrect json.
```java
private MappingJackson2HttpMessageConverter jackson2HttpMessageConverter() {
      ObjectMapper objectMapper = new ObjectMapper();
      // Setting true spits out wrong Swagger api-docs json
      objectMapper.configure(SerializationFeature.WRAP_ROOT_VALUE, true);
      objectMapper.registerModule(new Jdk7Module());

      MappingJackson2HttpMessageConverter converter = new   MappingJackson2HttpMessageConverter();
      converter.setObjectMapper(objectMapper);

      return converter;
}
```

this incorrect json ouput: 

    {
    "ResourceListing"{
        "apiVersion": "1.0",
        "apis": [
            {
                "description": "circuits",
                "path": "/default/circuits",
                "position": 0
            },
            {
                "description": "constructors",
                "path": "/default/constructors",
                "position": 1
            }
        ],
        "authorizations": {
            
        },
        "info": {
            "contact": "Contact Email",
            "description": "Api Description",
            "license": "Licence Type",
            "licenseUrl": "License URL",
            "termsOfServiceUrl": "Api terms of service",
            "title": "default Title"
        },
        "swaggerVersion": "1.2"
    }
    }

ResourceListing is missing a colon. 

I'm using Spring MVC Rest 4 + Jackson 2.4.4 + swagger-springmvc 0.9.5

**Comment by dilipkrish** [comment]
@t0tec not really sure if this is still relevant. I believe its fixed in 1.0.1

**Comment by t0tec** [comment]
Yes, only thing is when setting it to true swagger can't fetch the resource list. Probably because something goes wrong in the ui. Still I just changed WRAP_ROOT_VALUE to false. But it can cause problems with other people if they want to configure Jackson themselves.

**Comment by keesvandieren** [comment]
Problem indeed still exists when using Springfox 2.0.3.

Reproduced in 'hello world' project https://bitbucket.org/squins/springmvc-swagger-issues

To reproduce, clone this repo, uncomment relevant lines HelloWorldRestConfiguration method jackson2Converter, run the app and go to http://localhost:8099/rest/swagger-ui.html

**Comment by dilipkrish** [comment]
@keesvandieren I verified the problem! Not sure of a good way to fix it, based on the way spring message converters work. I've tried a bunch of things and they don't seem to work. Do you have a workaround or perhaps a solution that we could use. PR?

**Comment by ArnoldKesselaar** [comment]
Verified the issue still exists in Springfox 2.4.0.
After trying numerous different approaches a colleague and myself came across the following online resource by Marty Pitt: 
https://martypitt.wordpress.com/2012/11/05/custom-json-views-with-spring-mvc-and-jackson/

The resulting class allows the JSON root wrapping to be disabled only for Swagger. See attachment
[ViewAwareJsonMessageConverter.txt](https://github.com/springfox/springfox/files/255512/ViewAwareJsonMessageConverter.txt)

**Comment by arcadius** [comment]
Hi @ArnoldKesselaar 
Looking at the attached workaround, we will be having 2 ObjectMappers, 
- One ObjectMapper for Swagger with ```WRAP_ROOT_VALUE=false```
- One ObjectMapper for others with ```WRAP_ROOT_VALUE=true``` 

IMHO, this will make the swagger-ui.html work which is great ... 
But the JSON request/response shown in the Swagger-UI will be different from the one from the real API i.e the documents shown on the swagger-ui will have no root element.... 
Can you confirm @ArnoldKesselaar ?

Thanks.

**Comment by Chowdaryonpc** [comment]
I guess looks like this problem still exists.  Can some one help how to modify this class to just to ignore wrap root value just only for swagger?

`@Component
@Primary
public class CustomObjectMapper extends ObjectMapper 
{
    private static final long serialVersionUID = -6511257240128676961L;

    public CustomObjectMapper() {
        configure(DeserializationFeature.UNWRAP_ROOT_VALUE, true);
        configure(SerializationFeature.WRAP_ROOT_VALUE, true);
    }
    
    public String writeValueAsString(final Object obj, String rootName) {
        try {
          final ObjectWriter writer = writer().withRootName(rootName);
          return writer.writeValueAsString(obj);
        }  
        catch (Exception e) {
          throw new RuntimeException(e);
        }
    }
}`

**Comment by dilipkrish** [comment]
@Chowdaryonpc you can create mixins for the swagger classes

**Comment by hxp1178** [comment]
Is this issue resolved? I'm currently working with springfox v2.7.0 but I'm still facing the same issue. So can you please tell me what is the proper workaround to achieve root level wrapping?

**Comment by jpomykala** [comment]
Hey,
if somebody is also struggling with simmilar issue. I can recommend my library for that. You can enable response wrapping by @EnableResponseWrapping annotation and it works with SpringFox.
@hxp1178  In my case suggested solution with TypeResolver also didn't work. 😭

https://github.com/jpomykala/spring-higher-order-components

**Comment by nikhilsrivastava13** [comment]
Is this issue resolve? Does anyone have any solution fix for this?

**Comment by benjamin-Ndugga** [comment]
Hi Team, facing similar Issue , any workarounds?

**Comment by keuss** [comment]
Hi,

Still KO with SpringBoot 3.0.x and springdoc-openapi-starter-webmvc-ui  2.1.0 with `spring.jackson.serialization.wrap-root-value=true`, any workarounds ?

Thanks !
