### ISSUE TITLE
Question: what's the preferred way to override the v2 path?

### ISSUE THREAD

**Issue by who** [springfox/springfox#645]
The default base path for Swagger 2.0 spec is **/v2/api-docs**.

I would like to change this to be just **/api-docs**.

Unless I have the syntax wrong, from the looks of the `@RequestMapping` annotation in `Swagger2Controller`, there's a config parameter that can be used to do this.  However, even after adding springfox.documentatation.swagger.v2.path=/api-docs to my config, the path doesn't change.

I am loading my config strings via a `@Bean public static PropertySourcesPlaceholderConfigurer loadConfig()` function. My other config strings load and are available after the `PropertySourcesPlaceholderConfigurer` does it's duty.

**Comment by dilipkrish** [comment]
s/documentatation/documentation/g?

**Comment by who** [comment]
No, that's the [actual config string referenced in the controller](https://github.com/springfox/springfox/blob/416bbf1495979bd6cf55ebf813561e82be1b5697/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L50).

**Comment by Aloren** [comment]
@who I have the same issue. See: https://github.com/springfox/springfox/issues/642 :)

**Comment by dilipkrish** [comment]
Typo fixed but @Aloren is your property override working for you?

**Comment by Aloren** [comment]
@dilipkrish, yes. That works fine. @who, if you need help resolving the issue, feel free to ask :)

**Comment by who** [comment]
@Aloren Yes, I am still having an issue with this.  My config setting of `springfox.documentation.swagger.v2.path=/api-docs` isn't being populated into the `@RequestMapping` of `SwaggerController2`, so the Swagger2 spec is still being served from `/v2/api-docs` instead of `/api-docs`.

**Comment by dilipkrish** [comment]
@who is your ```PropertySourcesPropertyConfigurer``` a statically defined bean?

**Comment by Aloren** [comment]
@who add something like that to your code:
```
@PropertySource("classpath:swagger.properties")
@Configuration
public class SwaggerConfiguration {

//By this properties you can check which values were actually injected (should be used in tests)
@Value("${springfox.documentation.swagger.v2.path}")
private String swagger2Endpoint;
@Value("${springfox.documentation.swagger.v1.path}")
private String swagger1Endpoint;

}
```
If you follow standard maven folder layout -- add swagger.properties with the following content to src/main/resources folder:
springfox.documentation.swagger.v2.path=/api-docs
springfox.documentation.swagger.v1.path=/v1/api-docs

Make sure that SwaggerConfiguration's package is included into @ComponentScan basePackages value.

**Comment by who** [comment]
> @who is your PropertySourcesPropertyConfigurer a statically defined bean?

@dilipkrish Yes, it is.

@Aloren I am using `new ClassPathResource(myconfig.properties)` to load the file instead of `@PropertySource`.  I give the latter a shot.

**Comment by Aloren** [comment]
@who I haven't used ClassPathResource, but I think that is not a place from where properties get resolved by Spring. Have a look at: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/support/PropertySourcesPlaceholderConfigurer.html

**Comment by crm86** [comment]
I have the same issue. What is the final solution? I am still getting the default value for the version 2

**Comment by dilipkrish** [comment]
The solution is to use ```@PropertySource```

**Comment by gambour** [comment]
> @Configuration
@EnableSwagger2
@PropertySource({"classpath:swagger.properties"})
@ConditionalOnResource(resources = {"classpath:swagger.properties"})
@Profile("!test")
public class SwaggerConfig extends WebMvcAutoConfigurationAdapter {

and then in swagger.properties you put:

> `springfox.documentation.swagger.v2.path=rest/v1/api-docs`

it works for me :+1:

**Comment by prathap413** [comment]
I have a issue changing the Swagger-Ui URL. In integrated swager2 and swagger-ui using below dependencies
<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.4.0</version>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.4.0</version>
        </dependency>

Right now i am able to access to swagger Ui using : http://localhost:8080/<context-root>/rest/swagger-ui.html

So i want to change that URL to : http://localhost:8080/swagger or http://localhost:8080/<context-root>/swagger.

Can any one help me with this.

**Comment by miguelschwindt** [comment]
I'm using Spring 4.3 and Swagger v2. 

The solution of @gambour works fime for me.

**Comment by gambour** [comment]
@prathap413 this topic is talking about customising v2 path and not swagger-ui.html
swagger-ui.html is located in a webjar (added by spring boot to resources, see WebMvcAutoConfiguration addResourceHandlers)

to override this i think you should copy this file into your web resource or configure spring mvc so that the path /swagger show you your swagger-ui.html.

**Comment by umbreak** [comment]
The following configuration does not work for me:

````java
@SpringBootApplication
@EnableSwagger2
@PropertySource("classpath:application.properties")
public class Application {
    @Value("${springfox.documentation.swagger.v2.path}")
    private String swagger2Endpoint;

    @Bean
    public Docket swaggerSettings() {
        List<SecurityScheme> scheme = Lists.newArrayList(new BasicAuth("basicAuth"));
        return new Docket(DocumentationType.SWAGGER_2)
                .alternateTypeRules(newRule(typeResolver.resolve(DeferredResult.class,typeResolver.resolve(FileSystemResource.class)),
                                typeResolver.resolve(MultipartFile.class)))
                .securitySchemes(scheme)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build()
                .protocols(Sets.newHashSet("http"));
    }
}

And the application.properties (inside resources folder) contains: springfox.documentation.swagger.v2.path=/api-docs

However, on start, in the logs I still see:
2016-11-17 11:17:18.813  INFO 25602 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/v2/api-docs],methods=[GET],produces=[application/json || application/hal+json]}" onto public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)

**Comment by dilipkrish** [comment]
@umbreak this is fixed in 2.6.1

**Comment by kunalbhatia87** [comment]
I'm facing the same issue, even upgrading the version to 2.6.1
resources/swagger.properties `springfox.documentation.swagger.v2.path=/rest/docs`
swaggerconfig:-
`@PropertySource("classpath:swagger.properties")

@Value("${springfox.documentation.swagger.v2.path}")
    private String swagger2Endpoint;`

**Comment by dilipkrish** [comment]
You'd need to put your property source annotation @ the class level typically a `@Configuration` bean

**Comment by kunalbhatia87** [comment]
@dilipkrish , 
I have put the `@PropertySource` annotation on the class level, just like @Configuration. But still it does not work for me. I'm able to see the changed values in local, but when running on other environments, its still /v2/api-docs.

**Comment by umbreak** [comment]
I can confirm that in 2.6.1 it works

**Comment by kunalbhatia87** [comment]
I'm using an old version of spring boot i.e.
`Running with Spring Boot v1.2.7.RELEASE, Spring v4.1.8.RELEASE`. It does not work for me in the same. could that be a reason

**Comment by bobwenx** [comment]
2.6.1 does not work for me in the same.

**Comment by dilipkrish** [comment]
@bobwenx There are some improvements in the upcoming 2.7.0 release that will make this better.

**Comment by shivako** [comment]
Any help is appreciated. If I need to implement my own security ( I need to get access-token from Response's headers etc and stick this token with all further requests). How to do this kind of customization?

**Comment by kosikfl1** [comment]
I only have my phone. My computer is broken.  I'm trying to get money to get one and then come back.

**Comment by dilipkrish** [comment]
@shivako [Seen this](http://springfox.github.io/springfox/docs/current/#customizing-the-swagger-endpoints)

**Comment by xbmono** [comment]
This works for me and I can see springfox request is being sent to `/my/docs` the path I configured and I have an endpoint that is request mapped to that path but it still returns the default docs and my endpoint is not being called. Have I made a mistake or I didn't understand the whole point of this setting? Note: I want to return my own swagger.json instead of the one that springfox is using/generating
