### ISSUE TITLE
o.s.data.domain.Pageable - automatically add @ApiImplicitParams?

### ISSUE THREAD

**Issue by steve-oakey** [springfox/springfox#755]
Hi,

I have been looking for but haven't found a way to automatically the implicit parameters of the Pageable parameter. It would be great to have the page, size and sort parameters automatically added to the Swagger documentation. I have tried Docket#directModelSubstitute but this has not worked.

Any insight to this?

**Comment by tonisostrat** [comment]
I had the same problem in a Spring project and from what I could find there is no "automagical" way to do this. You have two options:
* Add _@ApiIgnore_ to the *Pageable* and then specify each element as _@ApiImplicitParam_
* Change the method signature to accept each element of the *Pageable* as a separate argument

Support for this is debatable. *Pageable* is a Spring-specific construct and who's to say it will never change? Baking something like this into a general framework sounds counter-productive.

**Comment by steve-oakey** [comment]
I agree, I am not suggesting that specific support for Pageable be written in. I was wondering if there was something in the Docket builder where I could configure my bean to say "if you see Pageable, use this class instead", where "this" class could be interpreted as request parameters (in the case of Pageable a class with page, size and sort fields).

**Comment by dilipkrish** [comment]
This should be fixed via #845

**Comment by steve-oakey** [comment]
Thanks!

**Comment by zdila** [comment]
It seems #845 only adds global parameters to every operation. I've found no way to specify that the parameter should be used only when `Pageable` has been found. Am I missing something or is it really not implemented?

**Comment by dilipkrish** [comment]
@zdila This was to only added implicit parameters to all operations. In your case it doesn't seem like the right solution. In your case, I would simply use an [alternate type rule](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot) for `Pageable` (see **10**).

**Comment by zdila** [comment]
OK, but description of this issue addresses exactly what I need but the provided solution can't be used for this.

I tried also the alternate type rule, but I can't use it to solve the problem.

What is needed is that for eg. `org.springframework.data.domain.Pageable` method parameter there should be created three `springfox.documentation.service.Parameter`s - for `page`, `offset` and `sort`, all with `paramType = "query"`.

**Comment by dilipkrish** [comment]
Assuming that you're creating a concrete pageable object `MyRequest`, adding setters for your page/offset/sort etc. __OR__ *jackson*ifying it a little should do the trick

```java
class MyRequest extends AbstractPageRequest {
@JsonCreator
 MyRequest(@JsonProperty("page) int page, @JsonProperty("size") int size) { super(...)}
 
 //additional bean properties with getters and setters
}
``

**Comment by zdila** [comment]
Pageable object is being created by Spring MVC.

**Comment by dilipkrish** [comment]
In which case you'd create a Jackson mixin

**Comment by zdila** [comment]
How can I tell the mixin properties that they should be represented as query paramerers?

Currently I have this on many places:

```java
    @ApiOperation(value = "Find partners")
    @ApiImplicitParams({
        @ApiImplicitParam(name = "page", dataType = "integer", paramType = "query",
                value = "Results page you want to retrieve (0..N)"),
        @ApiImplicitParam(name = "size", dataType = "integer", paramType = "query",
                value = "Number of records per page."),
        @ApiImplicitParam(name = "sort", allowMultiple = true, dataType = "string", paramType = "query",
                value = "Sorting criteria in the format: property(,asc|desc). " +
                        "Default sort order is ascending. " +
                        "Multiple sort criteria are supported.")
    })
    @RequestMapping(value = "/v1/partners", method = RequestMethod.GET)
    @ResponseBody
    @ResponseStatus(HttpStatus.OK)
    public List<Partner> findAll(@ApiIgnore final Pageable pageable) {
            ...
    }
```

I want to get rid of `@ApiImplicitParams`.

**Comment by zdila** [comment]
I think this issue should be reopened.

**Comment by dilipkrish** [comment]
I think you're 💯% correct.

**Comment by clajder** [comment]
@dilipkrish 
do you have any ETA on when this feature is implemented? I see target release 2.4.0 but not sure what time frame for this.

**Comment by dilipkrish** [comment]
![milestones_-_springfox_springfox](https://cloud.githubusercontent.com/assets/73257/11933105/5b91f72c-a7bf-11e5-98f8-6f69437c4ac3.jpg)

**Comment by marceloverdijk** [comment]
+1

**Comment by namkee** [comment]
I solve this problem through add custom ParameterBuilder.
i don't know implemented correctly.. anyway it works in my project.

    package springfox.documentation.swagger.readers.parameter;
     
    import com.fasterxml.classmate.TypeResolver;
    import java.util.List;
    import org.springframework.beans.factory.annotation.Autowired;
    import org.springframework.core.MethodParameter;
    import org.springframework.core.annotation.Order;
    import org.springframework.data.domain.Pageable;
    import org.springframework.stereotype.Component;
    import springfox.documentation.schema.ModelRef;
    import springfox.documentation.service.Parameter;
    import springfox.documentation.spi.DocumentationType;
    import springfox.documentation.spi.service.ParameterBuilderPlugin;
    import springfox.documentation.spi.service.contexts.ParameterContext;
    import springfox.documentation.swagger.common.SwaggerPluginSupport;
    import static com.google.common.collect.Lists.newArrayList;
     
    @Component
    @Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER)
    public class PageableParameterBuilder implements ParameterBuilderPlugin {
     
       private final TypeResolver typeResolver;
     
       @Autowired
       public PageableParameterBuilder(TypeResolver typeResolver) {
          this.typeResolver = typeResolver;
       } 
       @Override
       public boolean supports(DocumentationType delimiter) {
          return DocumentationType.SWAGGER_2.equals(delimiter);
       }     
       @Override
       public void apply(ParameterContext parameterContext) {
          MethodParameter param = parameterContext.methodParameter();
          if (param.getParameterType().equals(Pageable.class)) {
             List<Parameter> parameters = newArrayList();
             parameters.add(parameterContext.parameterBuilder()
                .parameterType("query").name("page").modelRef(new ModelRef("int"))
                .description("Results page you want to retrieve (0..N)").build());
             parameters.add(parameterContext.parameterBuilder()
                .parameterType("query").name("size").modelRef(new ModelRef("int"))
                .description("Number of records per page.").build());
             parameters.add(parameterContext.parameterBuilder()
                .parameterType("query").name("sort").modelRef(new ModelRef("string")).allowMultiple(true)
                .description("Sorting criteria in the format: property(,asc|desc)."
                   + "Default sort order is ascending. Multiple sort criteria are supported.").build());
             parameterContext.getOperationContext().operationBuilder().parameters(parameters);
          }
       }
    }

**Comment by steve-oakey** [comment]
@namkee - This has solved my issue. I needed to upgrade to version 2.4.0 for this to work, the previous version I was using (2.1.x) was not generating the parameters correctly.

**Comment by bluebilt** [comment]
Works like a charm, thanks namkee!

**Comment by hyeonu** [comment]
@namkee I've modified for multiple sort parameter.

```java
import static com.google.common.collect.Lists.newArrayList;
import static springfox.documentation.schema.ResolvedTypes.modelRefFactory;
import static springfox.documentation.spi.schema.contexts.ModelContext.inputParam;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.MethodParameter;
import org.springframework.core.annotation.Order;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Component;

import com.fasterxml.classmate.ResolvedType;
import com.fasterxml.classmate.TypeResolver;
import com.google.common.base.Function;

import springfox.documentation.schema.ModelReference;
import springfox.documentation.schema.TypeNameExtractor;
import springfox.documentation.service.Parameter;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spi.schema.contexts.ModelContext;
import springfox.documentation.spi.service.ParameterBuilderPlugin;
import springfox.documentation.spi.service.contexts.ParameterContext;
import springfox.documentation.swagger.common.SwaggerPluginSupport;

@Component
@Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER)
public class PageableParameterBuilderPlugin implements ParameterBuilderPlugin {
  private final TypeNameExtractor nameExtractor;
  private final TypeResolver resolver;

  @Autowired
  public PageableParameterBuilderPlugin(TypeNameExtractor nameExtractor, TypeResolver resolver) {
    this.nameExtractor = nameExtractor;
    this.resolver = resolver;
  }

  @Override
  public boolean supports(DocumentationType delimiter) {
    return true;
  }

  private Function<ResolvedType, ? extends ModelReference>
      createModelRefFactory(ParameterContext context) {
    ModelContext modelContext = inputParam(context.methodParameter().getParameterType(),
        context.getDocumentationType(),
        context.getAlternateTypeProvider(),
        context.getGenericNamingStrategy(),
        context.getIgnorableParameterTypes());
    return modelRefFactory(modelContext, nameExtractor);
  }

  @Override
  public void apply(ParameterContext context) {
    MethodParameter parameter = context.methodParameter();
    Class<?> type = parameter.getParameterType();
    if (type != null && Pageable.class.isAssignableFrom(type)) {
      Function<ResolvedType, ? extends ModelReference> factory =
          createModelRefFactory(context);

      ModelReference intModel = factory.apply(resolver.resolve(Integer.TYPE));
      ModelReference stringModel = factory.apply(resolver.resolve(List.class, String.class));

      List<Parameter> parameters = newArrayList(
          context.parameterBuilder()
              .parameterType("query").name("page").modelRef(intModel)
              .description("Results page you want to retrieve (0..N)")
              .build(),
          context.parameterBuilder()
              .parameterType("query").name("size").modelRef(intModel)
              .description("Number of recods per page")
              .build(),
          context.parameterBuilder()
              .parameterType("query").name("sort").modelRef(stringModel).allowMultiple(true)
              .description("Sorting criteria in the format: property(,asc|desc). "
                  + "Default sort order is ascending. "
                  + "Multiple sort criteria are supported.")
              .build());

      context.getOperationContext().operationBuilder().parameters(parameters);
    }
  }

}
```

**Comment by avineshsachan** [comment]
__

Can we set GlobalOperationParameters in Docket Bean at run time as a authentication Token:

docket.select()
.apis(RequestHandlerSelectors.any())
.paths(PathSelectors.any())
.build().globalOperationParameters(Lists.newArrayList(new ParameterBuilder()
.**name("sso-token")**
.description("Description of someGlobalParameter")
.modelRef(new ModelRef("string"))
.parameterType("header")
.required(true).defaultValue**_("Run Tme Value get from SSO Service")_**
.build()));

Please share a way to to it

Thanks in advance.

**Comment by IsmaTeddy** [comment]
@Namkee @hyeonu  
Thanks!!

**Comment by cbornet** [comment]
`context.methodParameter()` is deprecated on 2.6.0 so it must be replaced by `context.resolvedMethodParameter()`.
@dilipkrish could we have this plugin and maybe other useful ones somewhere in the code or in an "extras" artifact ?

**Comment by cbornet** [comment]
Only the class of course. The user will have to decide if he uses it or not by including it in a bean.

**Comment by dilipkrish** [comment]
@cbornet Yeah absolutely. Planning to re-organize the modules as its getting out of hand already 😒 Might add a another repo of useful plugins.

**Comment by tpolychniatis** [comment]
Thanks for the workaround @Namkee @hyeonu!

**Comment by Trii** [comment]
Quick note for anyone using @zdila's code up there. `dataType = integer` should be `dataType = int`.

**Comment by maxtuzz** [comment]
@tpolychniatis These are the changes I've also made to make it the builder plugin compatible with latest springfox release (2.6.1), but unfortunately my parameter inputs aren't showing up. Did you do anything else to make yours compatible?

**Comment by dilipkrish** [comment]
@maxtuzz Replace the condition with the following, just to be safe. Also verify the the breakpoint is hit. My guess is may be you haven't registered this builder as a bean.

```java
if (type != null && Pageable.class.isAssignableFrom(param.getParameterType().getErasedType()))
```

**Comment by 9numbernine9** [comment]
@tpolychniatis @dilipkrish I'm running into a similar issue with Springfox 2.6.x as well. What I've noticed is that the `apply` method in the `PageableParameterBuilder` is only correctly invoked with the `Pageable` type **if** the method in my controller that takes the `Pageable` parameter is annotated with something like `@ApiParam` or `@RequestParameter`. Without those annotations, when I debug the `apply` method in `PageableParameterBuilder`, the value returned by `param.getParameterType().getErasedType()` is actually `String.class` as opposed to the expected `Pageable.class`. I'm not sure if this is an expected change in behaviour in 2.6.x or not?

I should also probably mention that I've verified in the debugger that my Spring context does indeed have a `PageableParameterBuilder` bean in it at runtime. :-)

**Comment by tpolychniatis** [comment]
@9numbernine9 In may case the `Pageable` parameter in the controller is annotated with `@PageableDefault`

**Comment by 9numbernine9** [comment]
@tpolychniatis I don't think Springfox is interested in that annotation, so its presence or absence shouldn't have any effect. :-)

@dilipkrish I think the changes in dde6f4129c2a159bff38f6b9eac03522560023c0 (PR #1444) might be responsible for the change in behaviour with `Pageable` (and other types). Previously, `OptionalParameterReader#shouldExpand` would return `false` when looking at a `Pageable` parameter, which would cause the `parameters.add(pluginsManager.parameter(parameterContext))` line to get executed and trigger the correct evaluation of our `ParameterBuilderPlugin` with a `Pageable` parameter. Since dde6f4129c2a159bff38f6b9eac03522560023c0 , however, `shouldExpand` now returns `true` and the plugin doesn't get called correctly.

Is there a way to both keep the changes in #1444 and ensure that plugins are called with the same parameters as before this change?

**Comment by namkee** [comment]
after upgrade 2.6.0. it is difficult to support Pageable parameters.
So I changed it to implement OperationBuilderPlugin instead of ParameterBuilderPlugin.

`package springfox.documentation.spring.web.readers.operation;

import com.fasterxml.classmate.ResolvedType;
import com.fasterxml.classmate.TypeResolver;
import com.google.common.base.Function;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Component;
import springfox.documentation.builders.ParameterBuilder;
import springfox.documentation.schema.CoupangResolvedTypes;
import springfox.documentation.schema.CoupangTypeNameExtractor;
import springfox.documentation.schema.ModelReference;
import springfox.documentation.service.Parameter;
import springfox.documentation.service.ResolvedMethodParameter;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spi.schema.contexts.ModelContext;
import springfox.documentation.spi.service.OperationBuilderPlugin;
import springfox.documentation.spi.service.contexts.OperationContext;
import springfox.documentation.spi.service.contexts.ParameterContext;

import static com.google.common.collect.Lists.newArrayList;
import static springfox.documentation.spi.schema.contexts.ModelContext.inputParam;

@Component
@Order(Ordered.LOWEST_PRECEDENCE)
public class OperationPageableParameterReader implements OperationBuilderPlugin {
  private final CoupangTypeNameExtractor nameExtractor;
  private final TypeResolver resolver;
  private final ResolvedType pageableType;

  @Autowired
  public OperationPageableParameterReader(CoupangTypeNameExtractor nameExtractor, TypeResolver resolver) {
    this.nameExtractor = nameExtractor;
    this.resolver = resolver;
    this.pageableType = resolver.resolve(Pageable.class);
  }

  @Override
  public void apply(OperationContext context) {
    List<ResolvedMethodParameter> methodParameters = context.getParameters();
    List<Parameter> parameters = newArrayList();

    for (ResolvedMethodParameter methodParameter : methodParameters) {
      ResolvedType resolvedType = methodParameter.getParameterType();

      if (pageableType.equals(resolvedType)) {
        ParameterContext parameterContext = new ParameterContext(methodParameter,
            new ParameterBuilder(),
            context.getDocumentationContext(),
            context.getGenericsNamingStrategy(),
            context);
        Function<ResolvedType, ? extends ModelReference> factory = createModelRefFactory(parameterContext);

        ModelReference intModel = factory.apply(resolver.resolve(Integer.TYPE));
        ModelReference stringModel = factory.apply(resolver.resolve(List.class, String.class));

        parameters.add(new ParameterBuilder()
            .parameterType("query")
            .name("page")
            .modelRef(intModel)
            .description("Results page you want to retrieve (0..N)").build());
        parameters.add(new ParameterBuilder()
            .parameterType("query")
            .name("size")
            .modelRef(intModel)
            .description("Number of records per page").build());
        parameters.add(new ParameterBuilder()
            .parameterType("query")
            .name("sort")
            .modelRef(stringModel)
            .allowMultiple(true)
            .description("Sorting criteria in the format: property(,asc|desc). "
                + "Default sort order is ascending. "
                + "Multiple sort criteria are supported.")
            .build());
        context.operationBuilder().parameters(parameters);
      }
    }
  }

  @Override
  public boolean supports(DocumentationType delimiter) {
    return true;
  }

  private Function<ResolvedType, ? extends ModelReference> createModelRefFactory(ParameterContext context) {
    ModelContext modelContext = inputParam(context.resolvedMethodParameter().getParameterType().getErasedType(),
        context.getDocumentationType(),
        context.getAlternateTypeProvider(),
        context.getGenericNamingStrategy(),
        context.getIgnorableParameterTypes());
    return CoupangResolvedTypes.modelRefFactory(modelContext, nameExtractor);
  }
}`

**Comment by 9numbernine9** [comment]
@namkee That seems like a nice alternative for now. Kudos!

@dilipkrish Can do. I'll try to write up a new issue for this sometime today.

**Comment by 9numbernine9** [comment]
@dilipkrish I've created issue #1579 for this issue. Please have a read of that issue and let me know if everything seems clear.

**Comment by hartmut-pq** [comment]
@dilipkrish any plans for adding any of the above solutions directly to the lib? The one @namkee posted works smoothly with 2.6.1 - and I can't see why anyone would not want to use / benefit from having `Pageable` resolved automatically.

**Comment by hartmut-co-uk** [comment]
@dilipkrish any plans for adding any of the above solutions directly to the lib? The one @namkee posted works smoothly with 2.6.1 - and I can't see why anyone would not want to use / benefit from having Pageable resolved automatically.

**Comment by JakubBarta** [comment]
@namkee great job, works like a charm

**Comment by florianrusch** [comment]
@dilipkrish are there some plans for 2.7.0?

**Comment by dilipkrish** [comment]
@florianrusch thanks for the update! There are no plans for this in 2.7.0 but surely in the next release, to make things somewhat easier.

**Comment by hartmut-pq** [comment]
Plans for 2.7.1 ? :-)

**Comment by dilipkrish** [comment]
Did you try 2.7.0? I think this is covered for spring-data-rest

**Comment by hartmut-pq** [comment]
Hi @dilipkrish, finally had time to test with 2.7.0 - seems not to be working for me.
I'm not using spring-data-rest though - spring-data (spring-data-jpa) merely.

It's essentially a 
`org.springframework.data.domain.PageRequest` (extends `org.springframework.data.domain.AbstractPageRequest` implements `org.springframework.data.domain.Pageable`)

and does not seem to resolve the properties `page`, `size` & `sort`. The `OperationPageableParameterReader` update @florianrusch provided works fine though...

**Comment by dilipkrish** [comment]
@hartmut-pq Yeah thats the solution for non-spring-data-reset projects.

**Comment by dilipkrish** [comment]
@kent2171 Its waiting for contributions. Would love it if you'd be able to help out by implementing it

**Comment by dilipkrish** [comment]
Fixed via #2063

**Comment by Herzenkin** [comment]
@dilipkrish , still doesn't work with just plain "spring-data-jpa" on 2.8.0. Only with @florianrusch solution.

**Comment by dilipkrish** [comment]
@Herzenkin `spring-data-jpa` isnt supported as-is. It would have to be spring-data-rest.

**Comment by rhanton** [comment]
@dilipkrish That's disappointing for us spring-data-jpa people.

**Comment by dilipkrish** [comment]
@rhanton Not really sure, how that works. Is there a way to expose an JPA repository directly without having to write a controller or using spring-data-rest? Also its not that it will never be supported, there has just not been a demand for it.

**Comment by Herzenkin** [comment]
@dilipkrish , the question is exactly about writing custom controller with Pageable parameters which calls spring-data-jpa repository. It will be useful to "unbox" Pageable object in that case is it works with spring-data-rest repository.

**Comment by dilipkrish** [comment]
Oh I see. That makes sense. That is supported via extensibility, you could either do something [like how it is supported for spring data rest](http://springfox.github.io/springfox/docs/current/#creating-a-convention), or come up with a mixin class on your own and create an alternate type rule.

**Comment by cbornet** [comment]
I think what @rhanton meant is that the fix doesn't work with basic spring-mvc (and spring-data-jpa for persistence). We still need to include the `OperationBuilderPlugin` of @florianrusch . It would be nice to have this class embedded in the lib. Either as a simple class, or as a `@Component` bean that can be imported.

**Comment by dilipkrish** [comment]
@cbornet in case it wasn't obvious, you can create synthetic mixins as shown in the link above, modified snippet below...

```java

private Type pageableMixin() {
    return new AlternateTypeBuilder()
        .fullyQualifiedClassName(
            String.format("%s.generated.%s",
                Pageable.class.getPackage().getName(),
                Pageable.class.getSimpleName()))
        .withProperties(newArrayList(
            property(Integer.class, "page"),
            property(Integer.class, "limit"),
            property(String.class, "sort")
        ))
        .build();
  }

```

Will create a rule that will replace Pageable with a mixin class with properties "page, limit, sort" hardcoded. Does that make sense?

**Comment by 91wangmeng** [comment]
@dilipkrish i want size but i got pageSize when i use (@PageableDefault Pageable pageable)
![snipaste_2018-08-01_18-19-59](https://user-images.githubusercontent.com/13831315/43516237-8a461772-95b7-11e8-9809-89ef4ae4cc50.png)

**Comment by selvaebi** [comment]
The default findAll has page,sort and size , but the endpoint doesnt have a effect for any of the provided values. it returns all the object without paging.

below is my pom,
<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.8.0</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.8.0</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-data-rest</artifactId>
            <version>2.8.0</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-bean-validators</artifactId>
            <version>2.8.0</version>
        </dependency>

my repository resource,
@RepositoryRestResource
public interface PhenotypeRepository extends CrudRepository<Phenotype, String> {
}

**Comment by dilipkrish** [comment]
@91wangmeng you need to create a rule for the `Pageable` parameter with an alternate type like [described here](https://github.com/springfox/springfox/issues/755#issuecomment-393378205)

**Comment by dilipkrish** [comment]
Please upgrade to 2.9.2 @selvaebi

**Comment by vlsergeyatsbt** [comment]
Cleanup the existing parameters due to merge. Sadly, reflection is required.

````
import static com.google.common.collect.Lists.newArrayList;
import static springfox.documentation.spi.schema.contexts.ModelContext.inputParam;

import com.fasterxml.classmate.ResolvedType;
import com.fasterxml.classmate.TypeResolver;
import com.google.common.base.Function;
import com.google.common.collect.Sets;
import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import lombok.SneakyThrows;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Component;
import springfox.documentation.builders.OperationBuilder;
import springfox.documentation.builders.ParameterBuilder;
import springfox.documentation.schema.ModelReference;
import springfox.documentation.schema.ResolvedTypes;
import springfox.documentation.schema.TypeNameExtractor;
import springfox.documentation.service.Parameter;
import springfox.documentation.service.ResolvedMethodParameter;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spi.schema.contexts.ModelContext;
import springfox.documentation.spi.service.OperationBuilderPlugin;
import springfox.documentation.spi.service.contexts.OperationContext;
import springfox.documentation.spi.service.contexts.ParameterContext;

@Component
@Order(Ordered.LOWEST_PRECEDENCE)
public class OperationPageableParameterReader implements OperationBuilderPlugin {
    private final TypeNameExtractor nameExtractor;
    private final ResolvedType pageableType;
    private final TypeResolver resolver;

    @Autowired
    public OperationPageableParameterReader(TypeNameExtractor nameExtractor, TypeResolver resolver) {
        this.nameExtractor = nameExtractor;
        this.resolver = resolver;
        this.pageableType = resolver.resolve(Pageable.class);
    }

    @Override
    @SneakyThrows
    public void apply(OperationContext context) {
        List<ResolvedMethodParameter> methodParameters = context.getParameters();
        List<Parameter> parameters = newArrayList();

        for (ResolvedMethodParameter methodParameter : methodParameters) {
            ResolvedType resolvedType = methodParameter.getParameterType();
            if (!pageableType.equals(resolvedType)) {
                continue;
            }

            ParameterContext parameterContext = new ParameterContext(methodParameter, new ParameterBuilder(),
                    context.getDocumentationContext(), context.getGenericsNamingStrategy(), context);
            Function<ResolvedType, ? extends ModelReference> factory = createModelRefFactory(parameterContext);

            ModelReference intModel = factory.apply(resolver.resolve(Integer.TYPE));
            ModelReference stringModel = factory.apply(resolver.resolve(List.class, String.class));

            parameters.add(new ParameterBuilder().parameterType("query")
                    .name("page")
                    .modelRef(intModel)
                    .description("Results page you want to retrieve (0..N)")
                    .build());
            parameters.add(new ParameterBuilder().parameterType("query")
                    .name("size")
                    .modelRef(intModel)
                    .description("Number of records per page")
                    .build());
            parameters.add(new ParameterBuilder().parameterType("query")
                    .name("sort")
                    .modelRef(stringModel)
                    .allowMultiple(true)
                    .description("Sorting criteria in the format: property(,asc|desc). "
                            + "Default sort order is ascending. " + "Multiple sort criteria are supported.")
                    .build());

            final OperationBuilder operationBuilder = context.operationBuilder();
            operationBuilder.parameters(parameters);

            Set<String> toDelete = Sets.newLinkedHashSet(Arrays
                    .asList("offset", "pageNumber", "pageSize", "paged", "sort.sorted", "sort.unsorted", "unpaged"));
            final Field field = operationBuilder.getClass().getDeclaredField("parameters");
            field.setAccessible(true);
            @SuppressWarnings("unchecked")
            final List<Parameter> list = (List<Parameter>) field.get(operationBuilder);
            field.set(operationBuilder,
                    list.stream().filter(p -> !toDelete.contains(p.getName())).collect(Collectors.toList()));
        }
    }

    private Function<ResolvedType, ? extends ModelReference> createModelRefFactory(ParameterContext context) {
        ModelContext modelContext = inputParam(context.getGroupName(),
                context.resolvedMethodParameter().getParameterType(),
                context.getDocumentationType(),
                context.getAlternateTypeProvider(),
                context.getGenericNamingStrategy(),
                context.getIgnorableParameterTypes());
        return ResolvedTypes.modelRefFactory(modelContext, nameExtractor);
    }

    @Override
    public boolean supports(DocumentationType delimiter) {
        return true;
    }
}
````

**Comment by selvaebi** [comment]
> Please upgrade to 2.9.2 @selvaebi

sorry i used pagingAndSortingRepository , it worked in 2.8.0 , sorry for late reply.

**Comment by cbornet** [comment]
Hi @dilipkrish , I tested the `AlternateTypeRule` which works fine except that I can't set the parameter description. Is there a way to set it ?

**Comment by prisin** [comment]
@cbornet i am facing the same problem with AlternateTypeRule, is there any way to set description for pageable parameters ?
