### ISSUE TITLE
OAUTH problem

### ISSUE THREAD

**Issue by dorukokan** [springfox/springfox#834]
Hi,

I am trying to configure swagger oauth security and activate security button in the swagger interface by using springfox Docket as the following:

    public Docket swaggerSpringMvcPlugin()
    {
         return new Docket( DocumentationType.SWAGGER_2 )
			.groupName( "test" )
			.select()
				.apis( not( withMethodAnnotation( PrivateAPI.class )))
				.paths( regex( ".*/rest/.*" ) )
				.build().apiInfo( new ApiInfoBuilder()
					.title( "test" )
					.description( "test" )
					.version( "0.1" )
					.build())
				.securityContexts( Arrays.asList( SecurityContext.builder().securityReferences( SecurityReferences() ).build() ))
				.securitySchemes( securitySchemes());

     private List<SecurityScheme> securitySchemes()
	 {
		ArrayList<SecurityScheme> authorizationTypes = new ArrayList<>();
		
		List<AuthorizationScope> authorizationScopeList = new ArrayList<>();
		authorizationScopeList.add( new AuthorizationScope( "read", "read only" ) );
		authorizationScopeList.add( new AuthorizationScope( "write", "read and write" ) );
		
		List<GrantType> grantTypes = new ArrayList<>();
		TokenRequestEndpoint tokenRequestEndpoint = new TokenRequestEndpoint( "/oauth/token", "client_Id ", "client_secret" );
		grantTypes.add( new OAuth2ClientCredentialsGrantType( tokenRequestEndpoint ) );

		PasswordTokenRequestEndpoint passwordTokenRequestEndpoint = new PasswordTokenRequestEndpoint( "/oauth/token", "client_Id ", "client_secret", "user", "password" );
		grantTypes.add( new OAuth2PasswordCredentialsGrantType( passwordTokenRequestEndpoint ) );

		authorizationTypes.add( new OAuth( "oauth2", authorizationScopeList, grantTypes ) );

		return authorizationTypes;
	}

However, I get the following error and the swagger-ui.html cannot be loaded

Caused by: com.fasterxml.jackson.databind.JsonMappingException: Security scheme of type OAuth not supported (through reference chain: com.wordnik.swagger.models.Swagger["securityDefinitions"])

I could not figure out the problem with this. Do I miss something ?

**Comment by dilipkrish** [comment]
I think client credentials grant type isn't currently supported.

**Comment by dorukokan** [comment]
Thank you for the reply. Yes, I resolved that problem by removing client credentials grant type and the button showed up. 

However it's not clickable. I only use the Docket class to configure it as I pasted in the previous message. Do I miss something?

**Comment by dilipkrish** [comment]
This should've been fixed with 2.1.2. Could you confirm?

**Comment by Braamling** [comment]
As mentioned in #870, upgrading to 2.1.2 didn't solve this issue (I'm working on the same project as Dorukokan)

**Comment by vsafin-copart** [comment]
Ran into the same problem and I believe the issue is in swagger-ui.html

This function runs first to setup all authentication stuff: 

          function initializeSpringfox() {
            var security = {};
            window.springfox.securityConfig(function(data) {
              security = data;
              if (security.apiKey) {
                $('#input_apiKey').val(security.apiKey);
                addApiKeyAuthorization();
              }
              if (typeof initOAuth == "function") {
                if (security.clientId && security.appName && security.realm) {
                  initOAuth(security);
                }
              }
            });

Inside initOAuth you setting that button onClick event:

  $('.api-ic').click(function(s) {
    if($(s.target).hasClass('ic-off'))
      handleLogin();
    else {
      handleLogout();
    }
    false;
  });

Unfortunately - at that time NOTHING is loaded in <div id="swagger-ui-container" class="swagger-ui-wrap"></div> yet.

initializeSpringfox should be called in OnComplete handler here:

window.swaggerUi = new SwaggerUi({
            dom_id: "swagger-ui-container",
            supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
            onComplete: function(swaggerApi, swaggerUi) {

              $('pre code').each(function(i, e) {
                hljs.highlightBlock(e)
              });

            },
            onFailure: function(data) {
              log("Unable to Load SwaggerUI");
            },
            docExpansion: "none",
            apisSorter: "alpha"
          });

**Comment by vsafin-copart** [comment]
One more thing.. Authentication server redirects back to o2c.html and it should redirect to webjars/springfox-swagger-ui/o2c.html... need to adjust
